# Generated by Django 4.2.3 on 2023-07-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('media', models.CharField(max_length=100)),
                ('mensagem', models.TextField(verbose_name=350)),
            ],
        ),
    ]
