# Generated by Django 4.2.3 on 2023-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fredmagaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('technologies', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
            ],
        ),
    ]
