# Generated by Django 4.2.3 on 2023-11-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fredmagaweb', '0002_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
