# Generated by Django 4.2.3 on 2023-11-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fredmagaweb', '0003_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
