# Generated by Django 4.2.3 on 2024-08-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fredmagaweb', '0004_portfolioitem_publicado_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='curriculos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
            },
        ),
        migrations.AlterField(
            model_name='contato',
            name='empresa',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
