# Generated by Django 4.2.3 on 2024-08-15 20:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fredmagaweb', '0005_curriculo_alter_contato_empresa_alter_contato_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='certificates/')),
            ],
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='arquivo',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='curriculos/'),
        ),
    ]
