# Generated by Django 4.2.3 on 2024-08-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fredmagaweb', '0006_certificate_alter_curriculo_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default='', upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/thumbnails/'),
        ),
    ]
