# Generated by Django 4.2.3 on 2024-08-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fredmagaweb', '0007_remove_certificate_image_certificate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='file',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(default='', upload_to='certificates/'),
        ),
    ]
